
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}

baseurl: "/villages-in-the-city" # the subpath of your site, replace with the name of the github repository where you will host your site
url: "https://centerforspatialresearch.github.io/conflict_urbanism_sp2025/" # the base hostname & protocol for your site, e.g. http://github-username.io

title: Village in the City: Mapping the Relationship between Kampung Kota and Jakarta
author: Bimo Wicaksana, Dolyagritt Wonggom 
externallink: bw2814@columbia.edu | dw3090@columbia.edu #can include an external url here
description:  >- # this means to ignore newlines until "baseurl:"
  Put Abstract Here....


# Build settings - no need to change these

theme: minima
plugins:
  - jekyll-feed
